### Reception des informations venant de l'accéléromètre

POST http://localhost:8081/accelerometre
Content-Type: application/json

{
  "x": 0.0,
  "y": 0.0,
  "z": 0.0,
  "date": "2024-03-20"
}

### Reception de la distance parcourue par trajet

POST http://localhost:8081/distanceParcourue
Content-Type: application/json

{
  "distanceParourue": 1000,
  "date": "2024-03-20"
}

### Envoi des données du mois : le nombre d'infractions, la distance parcourue, le taux de réduction ainsi que le score

GET http://localhost:8081/informationsScore
